[features]
seeds = true
skip-lint = false

[programs.localnet]
skyhedge_protection = "5hGLEG1ts46iER4pfWnP1fMb8sG5nxSinNY1pjYnNPWx"

[programs.devnet]
skyhedge_protection = "5hGLEG1ts46iER4pfWnP1fMb8sG5nxSinNY1pjYnNPWx"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
