[features]
seeds = true
skip-lint = false

[programs.localnet]
skyhedge_protection = "7thTyPBaVCEBL2z28ojTxfmrbNMydXV3EAgbYgrz7GKr"

[programs.devnet]
skyhedge_protection = "7thTyPBaVCEBL2z28ojTxfmrbNMydXV3EAgbYgrz7GKr"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
